### PR TITLE
Added restricted software and updated osx configuration profiles.

### PR DESCRIPTION
**Pull request by tostart-pickagreatname**

### CODE REVIEW

**Comment by tostart-pickagreatname** [comment]
Thought: have you thought about including init_data in the accessible attributes of each object? Using individual attributes makes it difficult to automatically iterate through them, whereas we already have this hash of objects in init_data.  Unless I'm missing something and you know a good way to iterate?

**Comment by glenfarclas17** [comment]
I mainly have it there for converting into more ruby-like attributes... but,  can you give me an example of the kind of iteration you want to do?

**Comment by tostart-pickagreatname** [comment]
I was thinking of using it to populate a table of values, something like:
<% apiobject.init_data.each do |key, value| %>
  <%= key %>: <%= value %>
<% end %>
in a html.erb file.

**Comment by glenfarclas17** [comment]
Ahh totally makes sense.  My only thought is that the structure of each subclass, and the nature of the top-level keys in the init data,  is so wildly different that you'll get hard-to-read output, unless you use some kind of recursive formatter. 

Actually, YAML seems to make it decently readable (JSON would too).  Here's some noodling I just did in irb:

```ruby
require 'jss'
require 'erb'
include ERB::Util

class JSS::APIObject
  attr_reader :init_data
end

# connect to the API here....

####  Simple HTML table with data for a random computer
html_version = <<-ENDHTML
<html>
<body>
<% api_obj = JSS::Computer.new id: JSS::Computer.all_ids.sample %>
<table border="2px">
<tr><th>Key</th><th>Value</th></tr>
<% api_obj.init_data.each do |key, value| %>
<tr><td><%= h key %></td><td> <%= h value %></td></tr>
<% end %>
</table>
</body>
</html>
ENDHTML
output_file = Pathname.new "/tmp/foo.html"
output_file.open("w"){|f| f.write ERB.new(html_version).result }
system "open #{output_file}"

#### YAML data for a random computer in an html page
yaml_version = <<-ENDHTML
<html>
<body>
<% api_obj = JSS::Computer.new id: JSS::Computer.all_ids.sample %>
<pre>
<%= api_obj.init_data.to_yaml %>
</pre>
</body>
</html>
ENDHTML

output_file = Pathname.new "/tmp/foo.yaml.html"
output_file.open("w"){|f| f.write ERB.new(yaml_version).result }
system "open #{output_file}"
```

In any case, yes, having @init_data readable would make this kind of thing easier.

Another possible problem tho, is that if you retrieve an object, then change some of the values,  the values are now potentially out of sync with the init data, unless the getters/instance vars just refer to the init data.  To ensure consistency, you'd have to save your changes to the server and recreate the object again.

Just my thoughts on the matter.  I'm not against making the init_data readable, esp if we put some caveats in the documentation.

Cheers!
-Chris

**Comment by glenfarclas17** [comment]
Just merged it in - thanks SO much for contributing!  You're the first code-contributor to either of my github projects :-)  (and, as far as I know, you're probably the only other person who knows the innards of how ruby-jss works besides me!)  

Cheers!

**Pull request merged**
