### PR TITLE
OSX Configuration Profiles and Restricted Software

### PR DESCRIPTION
**Pull request by tostart-pickagreatname**
I created a restricted software APIObject. I have also added the OSX Configuration Profiles to the requires so that we can pull data about them via the gem.

### CODE REVIEW

**Comment by tostart-pickagreatname** [comment]
I might make some additional changes to the classes, so I'm going to close this for now and re-open when they're ready.

**Comment by glenfarclas17** [comment]
Sweet - thanks for contributing you're the first one! 

The OSXConfigProfile class accidently made it into a commit (oops)  - I hadn't actually finished it yet!  But as long as it isn't breaking things..

Feel free to email or hit me up in Macadmins Slack if you have questions! 

Cheers!
-Chris

**Comment by tostart-pickagreatname** [comment]
No problem Chris! I'll re-submit again in a little bit.

I'm only using the .all and .new requests. The payloads stuff should maybe be it's own object to include similar to self-service?

**Comment by glenfarclas17** [comment]
Heya Steven,

Hmm I could see doing something like that - esp. if people would want to use Ruby to work with the payload data itself.  Tho I'd be careful about how deep down the rabbit hole we want to get WRT modeling Apple's config profile plists as ruby classes :)

At the very least it's easy to parse the plist XML inside the payloads attribute into a Ruby Hash. From there It looks like the top-level "Payloads" object would be pretty simple, with just these attributes:

"PayloadUUID"=>String,
"PayloadType"=>STring,
"PayloadOrganization"=>String,
"PayloadIdentifier"=>String,
"PayloadDisplayName"=>String,
"PayloadDescription"=>String,
"PayloadVersion"=>Integer,
"PayloadEnabled"=>Boolean,
"PayloadRemovalDisallowed"=>Boolean,
"PayloadContent"=> Array of Hashes

I wouldn't bother mucking with the hashes inside the PayloadContent array,  tho perhaps providing some convenience methods to get their names or a hash of names => uuids.  The exact content of each one of them, aside from the 'Payload<x>' keys is too variable.

The question then is:  make this a module that adds some ability to a class when mixed in? (like 'SelfServable' or 'Scopable'... perhaps "ProfilePayloadable" )  or just define a standalone JSS::ProfilePayload class and have the OSXConfigurationProfile classe just have an attribute that contains one such object?

Speaking of that, one of my longer-term plans for OSXConfigurationProfile, is to subclass it from a generic ConfigurationProfile class, since MobileDevice and OSX profiles share most of their attributes.

The "ConfigurationProfile"  superclass (like "Group" or "ExtensionAttribute")  would encapsulate the shared attributes and methods, then the OSXConfigurationProfile and MobileDeviceConfigrationProfile subclasses (like ComputerGroup and MobileDeviceGroup) would deal with the specifics of each.

Anyway, that's more of a braindump on the subject that you probably wanted... let me know your thoughts!

-Chris

**Pull request closed without merging**
